version: "3"

services:

  mysql:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ecommercebe
      - MYSQL_USER=Ecommerce
      - MYSQL_PASSWORD=mysql